### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by BrandonZacharie** [mgcrea/node-plist-native#10]
```
9 errors generated.
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Brandon/Dropbox/Projects/HomeHero/Code/API/node_modules/plist-native/node_modules/libxmljs
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```

I believe this is because the dependency `libxmljs` is not up-to-date (`0.14.2`); the current version (`0.15.0`), works.

**Comment by BrandonZacharie** [comment]
After reinstalling (`npm uninstall plist-native && npm install plist-native`), it built. I'm not sure why `npm rebuild` didn't work.

**Comment by BrandonZacharie** [comment]
Before:
```
├─┬ plist-native@0.4.1
│ └─┬ libxmljs@0.14.2
│   ├── bindings@1.2.1
│   └── nan@1.8.4
```
After:
```
├─┬ plist-native@0.4.1
│ └─┬ libxmljs@0.14.3
│   ├── bindings@1.2.1
│   └── nan@2.0.7
```
