### ISSUE TITLE
error read info.plist of ipa file

### ISSUE THREAD

**Issue by nvcken** [mgcrea/node-plist-native#6]
```
Error: Start tag expected, '<' not found

    at Object.module.exports.fromXml (d:\Appota\appota_flight\node_modules\plist-native\no
de_modules\libxmljs\lib\document.js:120:21)
    at Object.exports.parseString (d:\Appota\appota_flight\node_modules\plist-native\lib\p
list-native.js:97:23)
    at Object.exports.parse (d:\Appota\appota_flight\node_modules\plist-native\lib\plist-n
ative.js:108:18)
    at Object.exports.install [as handle] (d:\Appota\appota_flight\routes\upbuild.js:243:2
5)
    at next_layer (d:\Appota\appota_flight\node_modules\express\lib\router\route.js:103:13
)
    at Route.dispatch (d:\Appota\appota_flight\node_modules\express\lib\router\route.js:10
7:5)
    at d:\Appota\appota_flight\node_modules\express\lib\router\index.js:205:24
    at param (d:\Appota\appota_flight\node_modules\express\lib\router\index.js:286:14)
    at param (d:\Appota\appota_flight\node_modules\express\lib\router\index.js:298:16)
    at Function.proto.process_params (d:\Appota\appota_flight\node_modules\express\lib\rou
ter\index.js:314:3)

```

**Comment by mgcrea** [comment]
Probably an issue with your file. Please provide a test case.
